.github/actions/changelog/README.md
.github/actions/changelog/main.yml

* New workflow added for automatic changelog
* Changelog should be automated process while creating new tag

feat: auto changelog workflow added

---

.github/workflows/tfsec.yml

* Updated workflow call from "workflow_dispatch" to 'workflow_call" with input of "working_directory"
* Took input variable where working directory is used
* Enhanced continuous integration for working directory and can be called from the modules.
* Took reference from other github workflows like changelog and SST workflow.

ci: Update tfsec workflow call and input for working directory

---

.github/workflows/tfsec/action.yml

* action added in separate directory .

ci: workflow added in diff direcotry

---

.github/workflows/helm.yml

* This shared workflow for helm action commands
* It contains the necessary commands required in Helm, such as 'helm lint', 'helm template', 'helm upgrade', and 'helm rollback

fix: shared workflow for helm actions

---

.github/workflows/tf-drift.yml

* Featured tf-drift workflow in the repo workflow. ( Call workflow in any github repository to use it )
* Automate Terraform to ensure the infrastructure in Azure and AWS remains consistent and prevent manual modifications.
* https://github.com/Azure-Samples/terraform-github-actions/blob/main/.github/workflows/tf-drift.yml

feat: Feautured tf-drift workflow

---

.github/workflows/helm.yml

* I have added Azure cloud provider with AWS cloud provider
* If we have a requirement on AWS or Azure we can use this workflow

fix: Added azure cloud provider

---

.github/workflows/tfdrift.yml

* Enhance the workflow by introducing a var_file variable that allows users to specify variable files for the Terraform plan. 
* Integrate the workflow with secrets inputs to streamline the installation of Azure CLI and AWS CLI.
* Updated the GitHub token in the github-script job.
* By variable addition simplifies the process of running the workflow, providing greater flexibility and ease of use.
* Secrets enhancement enables seamless setup and configuration of the required CLI tools, enhancing the overall efficiency and effectiveness of the workflow.
* Updated github token for enhanced security and improved integration with GitHub APIs and functionality.

feat: Update workflow to work with var files

---

.github/workflows/changelog.yml

* Changelog can run for the same repo.
* Need to create changelog for sharedworkflow .

feat: add changelog to call in sameworkflow

---

.github/workflows/tfdrift.yml

*  Added backend as a Terraform Cloud .
*  In some projects, there may be a requirement to use Terraform Cloud as the backend.

feat: Update workflow for compatible with backend as a terraform cloud

---

.github/workflows/auto-assignee.yml
.github/workflows/auto_assignee.yml
README.md
docs/auto-assignee.md

* Added auto assign assignee to the PR workflow.
* Added workflow which assigns assignee automatically to the PR which is opened or reopened.
* issue 437 https://github.com/clouddrove/Internal-tasks/issues/437

feat: added auto assign assignee to the PR workflow

---

.github/workflows/tfsec.yml

* tf-sec workflow modified to use in multiple orgs. 
* having issue to use inherite secrets in diff orgs .

fix: secret issue fixed to use in diff orgs.

---

.github/workflows/changelog.yml

* secret added as input for diff orgs . 
* interite secret is not working with multiple orgs.

fix: changelog updated to use secret in diff orgs.

---

.github/workflows/terraform.yml
README.md
docs/terraform-checks.md

* add terraform action workflow
* terraform action workflow help to init and plan to terraform code

ci: add terraform action workflow

---

.github/config/.tflint.hcl
.github/workflows/tf-checks.yml
.github/workflows/tf-lint.yml
README.md
docs/terraform-checks.md
docs/terraform-lint.md

* tf-lint and tf checks added . 
* To use tf checks and lint using shared workflow. 
* https://github.com/marketplace/actions/terraform-lint
-

feat: tf lint and checkes workflow added

---

.github/workflows/tfsec.yml

Upload sarif version has been updated for tfsec workflow.

fix: updated version for upload sarif in tfsec.

---

.github/workflows/checkov.yml
README.md
docs/checkov.md

* Checkov workflow added
* workflow should be used by shared workflow.

feat: checkov workflow added

---

.github/config/.tflint.hcl

* Updated aws plugin version from additional rules

feat: updated aws plugin version for tflint rules

---

.github/config/.tflint.hcl
.github/workflows/tf-lint.yml

- Changed done .tflint.hcl file with AWS version and deep-source
- Changed tflint.yml file with source-repo added.

feat: Updated tflint.hcl and tflint.yml files

---

.github/dependabot.yml
.github/workflows/changelog.yml
.github/workflows/docker-scanner.yml
.github/workflows/docker.yml
.github/workflows/sst_workflow.yml
.github/workflows/terraform_workflow.yml
.github/workflows/tfdrift.yml

* fixed yml files as per the yml-lint rules

fix: fixed yml files as per the yml-lint rules

---

.github/dependabot.yml
.github/workflows/auto_assignee.yml
.github/workflows/changelog.yml
.github/workflows/checkov.yml
.github/workflows/docker-scanner.yml
.github/workflows/docker.yml
.github/workflows/readme.yml
.github/workflows/sst_workflow.yml
.github/workflows/terraform.yml
.github/workflows/terraform_workflow.yml
.github/workflows/tf-checks.yml
.github/workflows/tf-lint.yml
.github/workflows/tfdrift.yml
.github/workflows/tfsec.yml
.github/workflows/ymllint.yml

* fixed yml files as per the yml-lint rules
https://github.com/clouddrove/github-shared-workflows/actions/runs/6047185249/job/16410146030

 fix: fixed yml files as per the yml-lint rules

---

.github/workflows/infracost.yml
README.md
docs/infracost.md

* Added infracost analysis workflow for calculation the resources cost and shows in PR comment.& generate actual report in artifactory.

feat: Added infracost analysis workflow

---

.github/workflows/cf-lint.yml
.github/workflows/terraform_workflow.yml
.github/workflows/ymllint-internal.yml
.github/workflows/ymllint.yml
docs/terraform_workflow.md

* Added workflow for cloudformation linter and security scan
* made yml linter workflow reusable
* Added TF var access token in environment variables
* Added attribute for minimum-approval in terraform workflow acceptace step

feat: Added workflow for cloudformation linter and security scan

---

.github/workflows/terraform_workflow.yml
docs/terraform_workflow.md

* Added attribute to pass environment variables as a input in terraform workflow
* Updated uses in Readme file

feat: Added attribute to pass environment variables as a input

---

.github/workflows/terraform_workflow.yml
.github/workflows/tfdrift.yml
docs/terraform_workflow.md

*  Added a feature to pass environment variables in Terraform workflows and TFDrift workflows.
* Resolved issues facing in tfdrift workflow

feat:  🚀 Added a feature to pass environment variables in Terraform workflows and TFDrift workflows.

---

.github/workflows/deploy-cloudformation.yml
README.md
docs/deploy-cloudformation.md

* Created cloudformation stack deploy reusable workflow.
* Created readme for cloudformation stack deploy workflow
* https://github.com/aws-controltower-examples/control-tower-example/actions/runs/6419650926/job/17430049980

feat: :rocket: Created cloudformation workflow and its readme

---

.github/workflows/deploy-cloudformation-stackset.yml

* Changed input region command for stack-instance for listing

feat: updated instance region for list command

---

.github/workflows/readme.yml
README.md
docs/readme.md

* Readme Generation shared workflow

feat: Created shared workflow for readme generator

---

.github/workflows/terraform_workflow.yml
docs/terraform_workflow.md

* Updated GCP authentication step

feat: Updated GCP Authentication step with required attributes

---

.github/workflows/tf-checks.yml

* Added GCP authentication step for tf-checks

feat: Added GCP authentication step for tf-checks

---

.github/workflows/tfsec.yml

* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.
* Provide the justifications for the changes (e.g. business case).
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.
* Link to any supporting jira issues or helpful documentation to add some context (e.g. stackoverflow).
* Use `closes #123`, if this PR closes a Jira issue `#123`

feat: update tfsec

---

.github/workflows/auto_merge.yml

* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.
* Provide the justifications for the changes (e.g. business case).
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.
* Link to any supporting jira issues or helpful documentation to add some context (e.g. stackoverflow).
* Use `closes #123`, if this PR closes a Jira issue `#123`

feat: updated wait for the checks

---

.github/workflows/tfdrift.yml

* Added GCP authentication steps in tfdrift

feat: :rocket:  Added GCP authentication steps in tfdrift

---

.github/workflows/terraform_workflow.yml
.github/workflows/tfdrift.yml

* Updated tfdift and terraform workflow with GCP auth steps

feat: updated gcp auth input & secrets

---

.github/workflows/terraform_workflow.yml
.github/workflows/tf-checks.yml
.github/workflows/tfdrift.yml

* Added input for GCP service-account create steps

Feat: Added GCP authentication more inputs

---

.github/workflows/smurf_docker_helm.yml

- added needs parameter in helm_lint_template job

fix: added needs parameter in helm_lint_template job

---

.github/workflows/tag-release.yml
docs/tag-release.md

- Introduced label-based semantic versioning to automate release tagging.
- Integrated tag-release.yaml from shared workflows.
- Added support for skipping tags using the no-tag label.
- Enhanced changelog generation on PR merges to main.
- Simplifies the release process by automating version bumps and changelogs.
- Reduces human error and ensures consistent versioning.
- Allows teams to skip tagging when needed for internal or non-release changes.

Feat : Added Release-Tag Workflow

---

.github/workflows/tf-pr-checks.yaml
CHANGELOG.md
README.md
docs/tf-pr-checks.md

* Created workflow which generate terraform plan with the PR and master branch and compare them
* This workflow make it easy to decide new release tag version, by comparing the both terraform plan from PR branch and master branch its easy to spot the changes and new resources

Terraform plan difference workflow

---

.github/workflows/helm.yml
docs/helm.md

- Added support for generating kube-diagram output from Helm templates.
- Uploaded the generated diagram as a GitHub Actions artifact.
- Improved rollback step to continue execution even if earlier steps fail.

Feat: updated helm shared workflow for kubediagram

---

.github/workflows/smurf_docker_helm.yml
.github/workflows/smurf_terraform.yml

* Update with new version tag: v1.1.4

Workflows files test

---

.github/workflows/terraform_workflow_target.yml

* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.
* Provide the justifications for the changes (e.g. business case).
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.
* Link to any supporting jira issues or helpful documentation to add some context (e.g. stackoverflow).
* Use `closes #123`, if this PR closes a Jira issue `#123`

fixes the conflicts and description spell mistake
